#receivers:
#  filelog:
#    include: [ /var/log/*.log ]
receivers:
  promtail:
    config:
      positions:
        filename: /tmp/positions.yaml
        sync_period: 10s
      scrape_configs:
        - job_name: system
          static_configs:
            - labels:
                job: varlogs
                __path__: /var/log/example.log
      target_config:
        sync_period: 10s

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    logs:
      receivers: [ promtail ]
      processors: [ batch ]
      exporters: [ logging ]