receivers:
  filelog:
    include: [ /var/log/*.log ]
#receivers:
#  promtail:
#    config:
#      positions:
#        filename: /tmp/positions.yaml
#      scrape_configs:
#        - job_name: system
#          static_configs:
#            - labels:
#                job: varlogs
#                __path__: /var/log/*log

processors:
  batch:

exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ batch ]
      exporters: [ logging ]